# This is a basic workflow to help you get started with Actions

name: Main Testing & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "test"
  test:
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest tests -sxv --cov=quickscript --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: PSU3D0/quickscript
          files: ./coverage.xml
